CC=cl.exe
LINK=link.exe

App: Compile
	$(LINK) /OUT:"../GeonamesSpatialApp.exe" "../GeonamesSpatialApp.obj"

Compile:
	$(CC) /c /MD /W4 /EHsc /O2 "../GeonamesSpatialApp.cpp" /Fo:"../GeonamesSpatialApp.obj"
